// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/app_filter_tabs/data/repositories/categories_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flowers_app/config/base_response/result.dart' as _i4;
import 'package:flowers_app/features/app_filter_tabs/data/datasources/app_filter_tabs_remote_data_source_contract.dart'
    as _i2;
import 'package:flowers_app/features/app_filter_tabs/data/models/categories_response_dto.dart'
    as _i5;
import 'package:flowers_app/features/app_filter_tabs/data/models/occasions_response_dto.dart'
    as _i8;
import 'package:flowers_app/features/app_filter_tabs/domain/entities/app_filter_tabs_params.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AppFilterTabsRemoteDataSourceContract].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppFilterTabsRemoteDataSourceContract extends _i1.Mock
    implements _i2.AppFilterTabsRemoteDataSourceContract {
  MockAppFilterTabsRemoteDataSourceContract() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.CategoriesResponseDto>> getAllCategories({
    required _i6.AppFilterTabsParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllCategories, [], {#params: params}),
            returnValue:
                _i3.Future<_i4.Result<_i5.CategoriesResponseDto>>.value(
                  _i7.dummyValue<_i4.Result<_i5.CategoriesResponseDto>>(
                    this,
                    Invocation.method(#getAllCategories, [], {#params: params}),
                  ),
                ),
          )
          as _i3.Future<_i4.Result<_i5.CategoriesResponseDto>>);

  @override
  _i3.Future<_i4.Result<_i8.OccasionsResponseDto>> getAllOccasions({
    required _i6.AppFilterTabsParams? params,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllOccasions, [], {#params: params}),
            returnValue: _i3.Future<_i4.Result<_i8.OccasionsResponseDto>>.value(
              _i7.dummyValue<_i4.Result<_i8.OccasionsResponseDto>>(
                this,
                Invocation.method(#getAllOccasions, [], {#params: params}),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i8.OccasionsResponseDto>>);
}
