// Mocks generated by Mockito 5.4.6 from annotations
// in flowers_app/test/features/login/data/repositories/login_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flowers_app/config/base_response/result.dart' as _i6;
import 'package:flowers_app/config/uses_cases/login_params.dart' as _i8;
import 'package:flowers_app/features/login/api/datasources/login_local_data_source_impl.dart'
    as _i3;
import 'package:flowers_app/features/login/api/datasources/login_remote_data_source_impl.dart'
    as _i5;
import 'package:flowers_app/features/login/data/models/login_response_model.dart'
    as _i7;
import 'package:flowers_app/features/login/data/models/user_model.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginLocalDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginLocalDataSourceImpl extends _i1.Mock
    implements _i3.LoginLocalDataSourceImpl {
  MockLoginLocalDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.UserModel> saveUser(_i2.UserModel? userModel) =>
      (super.noSuchMethod(
            Invocation.method(#saveUser, [userModel]),
            returnValue: _i4.Future<_i2.UserModel>.value(
              _FakeUserModel_0(this, Invocation.method(#saveUser, [userModel])),
            ),
          )
          as _i4.Future<_i2.UserModel>);

  @override
  _i4.Future<_i2.UserModel?> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i4.Future<_i2.UserModel?>.value(),
          )
          as _i4.Future<_i2.UserModel?>);
}

/// A class which mocks [LoginRemoteDataSourceImpl].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRemoteDataSourceImpl extends _i1.Mock
    implements _i5.LoginRemoteDataSourceImpl {
  MockLoginRemoteDataSourceImpl() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i6.Result<_i7.LoginResponseModel>> login(
    _i8.LoginParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [params]),
            returnValue: _i4.Future<_i6.Result<_i7.LoginResponseModel>>.value(
              _i9.dummyValue<_i6.Result<_i7.LoginResponseModel>>(
                this,
                Invocation.method(#login, [params]),
              ),
            ),
          )
          as _i4.Future<_i6.Result<_i7.LoginResponseModel>>);
}
